basePath: /api
definitions:
  routers.PingDocsScheme:
    properties:
      docs:
        description: 指向 Swagger UI 文档格式的页面
        example: /docs/index.html
        type: string
      redoc:
        description: 指向 Redoc 文档格式的页面
        example: /redoc
        type: string
    required:
    - docs
    - redoc
    type: object
  routers.PingOutputScheme:
    properties:
      current:
        description: 当前日期时间字符串
        example: "2025-01-08 10:25:20"
        type: string
      docs:
        allOf:
        - $ref: '#/definitions/routers.PingDocsScheme'
        description: 接口文档
      message:
        description: 保留字段
        example: pong
        type: string
      run_at:
        description: 服务启动时的日期时间字符串
        example: "2025-01-08 10:25:20"
        type: string
      run_at_ts:
        description: 服务启动时的时间戳
        example: 1736303120
        type: integer
      timestamp:
        description: 当前时间戳
        example: 1736303120
        type: integer
      version:
        description: 版本号
        example: 0.1.0
        type: string
    required:
    - current
    - docs
    - message
    - run_at
    - run_at_ts
    - timestamp
    - version
    type: object
  xml.ConvertXMLInput:
    properties:
      content:
        description: xml 字符串
        example: <note><to>value</to></note>
        type: string
    required:
    - content
    type: object
  xml.ConvertXMLOutput:
    properties:
      content:
        description: json 字符串
        example: '{"note": {"to": "value"}}'
        type: string
    required:
    - content
    type: object
info:
  contact: {}
  title: go-proxy-api
  version: 0.1.2
paths:
  /:
    get:
      consumes:
      - application/json
      description: Ping
      operationId: /.get
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routers.PingOutputScheme'
      summary: Ping
      tags:
      - ""
  /apple/location/{code}:
    get:
      description: 返回 code 文本
      operationId: apple.location.code
      parameters:
      - description: 地区代码
        example: US
        in: path
        name: code
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Location Code
      tags:
      - Apple
  /convert/svg/png:
    get:
      description: 将 SVG 图片转为 png
      operationId: convert.svg.png.get
      parameters:
      - description: svg图片地址
        example: https://www.docker.com/wp-content/uploads/2024/01/icon-docker-square.svg
        in: query
        name: url
        required: true
        type: string
      - description: 是否下载
        example: false
        in: query
        name: download
        type: boolean
      produces:
      - image/png
      responses:
        "200":
          description: OK
      summary: SVG to PNG
      tags:
      - convert
  /convert/xml/json:
    get:
      consumes:
      - application/json
      description: 将传入的 xml 字符串转成 json字符串并返回
      operationId: convert.xml.json.get
      parameters:
      - description: xml字符串
        in: query
        name: content
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/xml.ConvertXMLOutput'
      summary: XML to JSON
      tags:
      - convert
    post:
      consumes:
      - application/json
      description: 将传入的 xml 字符串转成 json字符串并返回
      operationId: convert.xml.json.post
      parameters:
      - description: '-'
        in: body
        name: content
        required: true
        schema:
          $ref: '#/definitions/xml.ConvertXMLInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/xml.ConvertXMLOutput'
      summary: XML to JSON
      tags:
      - convert
  /ping:
    get:
      consumes:
      - application/json
      description: Ping
      operationId: ping.get
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routers.PingOutputScheme'
      summary: Ping
      tags:
      - ""
swagger: "2.0"
