basePath: /api
definitions:
  routers.PingDocsScheme:
    properties:
      docs:
        description: 指向 Swagger UI 文档格式的页面
        example: /docs/index.html
        type: string
      redoc:
        description: 指向 Redoc 文档格式的页面
        example: /redoc
        type: string
    required:
    - docs
    - redoc
    type: object
  routers.PingOutputScheme:
    properties:
      current:
        description: 当前日期时间字符串
        example: "2025-01-08 10:25:20"
        type: string
      docs:
        allOf:
        - $ref: '#/definitions/routers.PingDocsScheme'
        description: 接口文档
      message:
        description: 保留字段
        example: pong
        type: string
      run_at:
        description: 服务启动时的日期时间字符串
        example: "2025-01-08 10:25:20"
        type: string
      run_at_ts:
        description: 服务启动时的时间戳
        example: 1736303120
        type: integer
      timestamp:
        description: 当前时间戳
        example: 1736303120
        type: integer
      version:
        description: 版本号
        example: 0.1.0
        type: string
    required:
    - current
    - docs
    - message
    - run_at
    - run_at_ts
    - timestamp
    - version
    type: object
  xml.ConvertXMLInput:
    properties:
      content:
        example: <note><to>value</to></note>
        type: string
    required:
    - content
    type: object
  xml.ConvertXMLOutput:
    properties:
      content:
        example: '{"note": {"to": "value"}}'
        type: string
    required:
    - content
    type: object
info:
  contact: {}
  title: go-proxy-api
  version: 0.1.1
paths:
  /:
    get:
      consumes:
      - application/json
      description: Ping
      operationId: /.get
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routers.PingOutputScheme'
      summary: Ping
      tags:
      - ""
  /convert/xml/json:
    get:
      consumes:
      - application/json
      description: 将传入的 xml 字符串转成 json字符串并返回
      operationId: convert.xml.json.get
      parameters:
      - description: xml 字符串
        in: query
        name: content
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/xml.ConvertXMLOutput'
      summary: XML 转 JSON
      tags:
      - convert
    post:
      consumes:
      - application/json
      description: 将传入的 xml 字符串转成 json字符串并返回
      operationId: convert.xml.json.post
      parameters:
      - description: 输入对象
        in: body
        name: content
        required: true
        schema:
          $ref: '#/definitions/xml.ConvertXMLInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/xml.ConvertXMLOutput'
      summary: XML 转 JSON
      tags:
      - convert
  /ping:
    get:
      consumes:
      - application/json
      description: Ping
      operationId: ping.get
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routers.PingOutputScheme'
      summary: Ping
      tags:
      - ""
swagger: "2.0"
