services:
  go-proxy-api:
    container_name: go-proxy-api
    platform: linux/amd64
    ports:
      - 8000:8000
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    labels:
      - dev.orbstack.domains=go-proxy-api.orb.local
